
print("ninad")
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
print(f"The sum is {num1 + num2}")   
print("ninad")
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
print(f"The sum is {num1 + num2}")   
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
print(f"The sum is {num1 + num2}")   
